id: I488B18E0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:25:53+00:00'
last_modified: '2022-06-09T04:55:24.023284+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD401
  title: སྨན་ཐང་རྒྱས་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0FB6:
      image_group_id: I3PD421
      title: Volume 1 of sman thang rgyas 'grel/
      total_pages: 414
      order: 1
      base_file: 0FB6.txt
    9EA0:
      image_group_id: I3PD422
      title: Volume 2 of sman thang rgyas 'grel/
      total_pages: 414
      order: 2
      base_file: 9EA0.txt
    4C6E:
      image_group_id: I3PD423
      title: Volume 3 of sman thang rgyas 'grel/
      total_pages: 410
      order: 3
      base_file: 4C6E.txt
    921F:
      image_group_id: I3PD424
      title: Volume 4 of sman thang rgyas 'grel/
      total_pages: 410
      order: 4
      base_file: 921F.txt
    CFE7:
      image_group_id: I3PD425
      title: Volume 5 of sman thang rgyas 'grel/
      total_pages: 402
      order: 5
      base_file: CFE7.txt
    '6194':
      image_group_id: I3PD426
      title: Volume 6 of sman thang rgyas 'grel/
      total_pages: 410
      order: 6
      base_file: 6194.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
