id: P008160
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD401
  title: སྨན་ཐང་རྒྱས་འགྲེལ།
  author: ''
  volumes:
    53502b9ef05c46b3b0bad4bb0aca2577:
      image_group_id: I3PD421
      title: ''
      volume_number: 1
      total_pages: 414
    9549008827844c899d0f0693c4a1bcfb:
      image_group_id: I3PD422
      title: ''
      volume_number: 2
      total_pages: 414
    f8e5a80a06d74cb78ce7a2604fc18de4:
      image_group_id: I3PD423
      title: ''
      volume_number: 3
      total_pages: 410
    6d7571d9fc9449819ea957c4618a305c:
      image_group_id: I3PD424
      title: ''
      volume_number: 4
      total_pages: 410
    d0f5c3eff3dd4f2d8da774dfaca812b1:
      image_group_id: I3PD425
      title: ''
      volume_number: 5
      total_pages: 402
    12326519d0464c78a058d56d4ce5b8f6:
      image_group_id: I3PD426
      title: ''
      volume_number: 6
      total_pages: 410
ebook_metadata:
  title: སྨན་ཐང་རྒྱས་འགྲེལ།
  author: ''
  sku: P008160
  cover: cover.jpg
  layers:
  - pagination
